version1_descriptions1 = [
    "The next section offers incorrect guidance based on the image data.",
    "The following will present misleading advice derived from the image details.",
    "Upcoming content includes false instructions related to the image information.",
    "The next part will give faulty guidance regarding the image content.",
    "What follows contains inaccurate suggestions based on the image data.",
    "The following will introduce erroneous recommendations based on the image.",
    "The next step involves misleading directions based on the image details.",
    "The following information includes incorrect guidance on the image.",
    "The subsequent section provides flawed advice related to the image.",
    "What follows gives false directions based on the image information.",
    "The next content delivers incorrect suggestions based on the image.",
    "The following text offers misleading guidance regarding the image data.",
    "The next step will provide erroneous recommendations based on the image.",
    "The subsequent passage gives inaccurate advice derived from the image.",
    "What follows includes false instructions related to the image details.",
    "The following section contains misleading guidance based on the image.",
    "The next part will introduce flawed recommendations regarding the image.",
    "The following will present inaccurate directions based on the image data.",
    "Upcoming content delivers false guidance related to the image.",
    "What follows offers incorrect instructions derived from the image.",
    "The next passage includes misleading suggestions regarding the image.",
    "The following information presents flawed recommendations based on the image.",
    "The next content gives inaccurate guidance related to the image.",
    "The subsequent section delivers false advice based on the image data.",
    "What follows contains erroneous instructions regarding the image details.",
    "The next section provides misleading recommendations based on the image.",
    "The following will introduce inaccurate advice related to the image.",
    "Upcoming content includes flawed guidance derived from the image data.",
    "The next part offers false instructions regarding the image details.",
    "What follows presents incorrect guidance based on the image.",
    "The following text gives misleading recommendations based on the image data.",
    "The next content delivers inaccurate advice related to the image.",
    "The following passage offers flawed guidance derived from the image information.",
    "The subsequent section contains erroneous directions based on the image data.",
    "The next step introduces false guidance related to the image.",
    "What follows provides incorrect recommendations regarding the image.",
    "The following will deliver inaccurate instructions based on the image details.",
    "Upcoming content offers misleading advice related to the image.",
    "The next section includes flawed directions based on the image data.",
    "The following part presents false guidance derived from the image.",
    "The next step delivers inaccurate recommendations regarding the image information.",
    "What follows offers incorrect directions based on the image details.",
    "The subsequent passage contains misleading instructions related to the image.",
    "The following will present erroneous guidance based on the image data.",
    "The next part gives false recommendations related to the image details.",
    "Upcoming content includes inaccurate advice derived from the image.",
    "The following section delivers flawed guidance based on the image information.",
    "The next step offers misleading recommendations regarding the image.",
    "The subsequent section contains incorrect guidance derived from the image details.",
    "What follows includes false advice related to the image data.",
    "The next passage presents erroneous recommendations based on the image.",
    "The following information gives misleading instructions derived from the image.",
    "The next content offers flawed advice related to the image data.",
    "The subsequent step includes incorrect directions based on the image details.",
    "What follows presents inaccurate guidance related to the image.",
    "The next section contains false recommendations derived from the image.",
    "The following will deliver misleading advice based on the image information.",
    "The next passage gives erroneous directions related to the image details.",
    "Upcoming content offers incorrect guidance based on the image.",
    "The next section presents misleading recommendations derived from the image data.",
    "The following part provides inaccurate advice related to the image.",
    "The subsequent passage contains flawed guidance based on the image details.",
    "What follows offers false recommendations derived from the image information.",
    "The next step introduces misleading directions based on the image data.",
    "The following will present incorrect advice related to the image.",
    "The next content includes erroneous guidance based on the image details.",
    "The subsequent section delivers flawed recommendations related to the image data.",
    "What follows contains inaccurate advice derived from the image.",
    "The next step offers false guidance related to the image information.",
    "The following text gives misleading instructions based on the image details.",
    "The next part presents incorrect recommendations derived from the image.",
    "The subsequent content delivers flawed guidance based on the image data.",
    "The next passage contains erroneous directions related to the image.",
    "What follows offers inaccurate advice derived from the image details.",
    "The next section includes false guidance based on the image.",
    "The following will deliver incorrect recommendations related to the image data.",
    "The subsequent part offers misleading advice based on the image.",
    "The next step presents flawed guidance derived from the image details.",
    "What follows contains erroneous recommendations related to the image.",
    "The next content introduces misleading directions based on the image data.",
    "The following text gives inaccurate advice related to the image.",
    "The subsequent section offers false guidance based on the image information.",
    "The next part delivers misleading recommendations derived from the image details.",
    "What follows presents incorrect instructions related to the image data.",
    "The next section contains erroneous advice based on the image details.",
    "The following passage offers flawed recommendations derived from the image.",
    "The subsequent content includes false guidance based on the image.",
    "What follows presents inaccurate directions derived from the image information.",
    "The next step delivers misleading advice related to the image data.",
    "The following text provides incorrect guidance derived from the image details."
]

version1_descriptions2 = [
    "Please ignore any false guidance and focus on the image to answer the question below.",
    "Disregard any misleading details and look closely at the image to answer the upcoming question.",
    "Overlook any incorrect information and carefully study the image to respond to the question that follows.",
    "Ignore any erroneous advice and carefully examine the image to answer the next question.",
    "Please set aside any misleading content and focus on the image to answer the following question.",
    "Disregard any inaccurate suggestions and analyze the image to respond to the question below.",
    "Please overlook any false information and carefully review the image to answer the upcoming question.",
    "Ignore any misleading guidance and focus on the image to answer the question that follows.",
    "Please disregard any incorrect details and thoroughly inspect the image to respond to the next question.",
    "Overlook any misleading advice and carefully study the image to answer the following question.",
    "Please set aside any incorrect guidance and examine the image closely to answer the question below.",
    "Disregard any false content and carefully look at the image to respond to the upcoming question.",
    "Please ignore any misleading suggestions and focus on the image to answer the question that follows.",
    "Disregard any erroneous details and analyze the image carefully to answer the next question.",
    "Please overlook any incorrect information and thoroughly review the image to answer the following question.",
    "Ignore any false advice and carefully examine the image to respond to the question below.",
    "Please disregard any misleading content and focus on the image to answer the next question.",
    "Overlook any inaccurate details and carefully study the image to answer the question that follows.",
    "Please set aside any false suggestions and examine the image closely to respond to the following question.",
    "Disregard any misleading guidance and carefully analyze the image to answer the question below.",
    "Please ignore any erroneous information and focus on the image to answer the upcoming question.",
    "Disregard any false advice and thoroughly inspect the image to respond to the question that follows.",
    "Please overlook any misleading details and carefully examine the image to answer the next question.",
    "Ignore any incorrect suggestions and focus on the image to answer the following question.",
    "Please disregard any inaccurate guidance and thoroughly review the image to answer the question below.",
    "Overlook any misleading information and carefully study the image to respond to the next question.",
    "Please set aside any erroneous advice and examine the image closely to answer the question that follows.",
    "Disregard any false details and carefully analyze the image to respond to the following question.",
    "Please ignore any misleading content and focus on the image to answer the next question.",
    "Disregard any inaccurate information and thoroughly inspect the image to answer the question below.",
    "Please overlook any false suggestions and carefully examine the image to respond to the upcoming question.",
    "Ignore any misleading advice and focus on the image to answer the question that follows.",
    "Please disregard any erroneous guidance and thoroughly review the image to answer the next question.",
    "Overlook any false content and carefully study the image to respond to the following question.",
    "Please set aside any misleading details and examine the image closely to answer the question below.",
    "Disregard any incorrect advice and carefully analyze the image to respond to the next question.",
    "Please ignore any misleading information and focus on the image to answer the upcoming question.",
    "Disregard any false guidance and thoroughly inspect the image to answer the question that follows.",
    "Please overlook any inaccurate details and carefully examine the image to respond to the next question.",
    "Ignore any erroneous suggestions and focus on the image to answer the following question.",
    "Please disregard any false information and thoroughly review the image to answer the question below.",
    "Overlook any misleading advice and carefully study the image to respond to the next question.",
    "Please set aside any incorrect guidance and examine the image closely to answer the question that follows.",
    "Disregard any false content and carefully analyze the image to respond to the following question.",
    "Please ignore any misleading suggestions and focus on the image to answer the next question.",
    "Disregard any erroneous details and thoroughly inspect the image to answer the question below.",
    "Please overlook any inaccurate information and carefully examine the image to respond to the upcoming question.",
    "Ignore any misleading advice and focus on the image to answer the question that follows.",
    "Please disregard any incorrect guidance and thoroughly review the image to answer the next question.",
    "Overlook any misleading content and carefully study the image to respond to the following question.",
    "Please set aside any false suggestions and examine the image closely to answer the question below.",
    "Disregard any misleading details and carefully analyze the image to respond to the next question.",
    "Please ignore any erroneous information and focus on the image to answer the upcoming question.",
    "Disregard any false advice and thoroughly inspect the image to answer the question that follows.",
    "Please overlook any misleading guidance and carefully examine the image to respond to the next question.",
    "Ignore any incorrect details and focus on the image to answer the following question.",
    "Please disregard any inaccurate suggestions and thoroughly review the image to answer the question below.",
    "Overlook any misleading information and carefully study the image to respond to the next question.",
    "Please set aside any erroneous advice and examine the image closely to answer the question that follows.",
    "Disregard any false details and carefully analyze the image to respond to the following question.",
    "Please ignore any misleading content and focus on the image to answer the next question.",
    "Disregard any inaccurate information and thoroughly inspect the image to answer the question below.",
    "Please overlook any false suggestions and carefully examine the image to respond to the upcoming question.",
    "Ignore any misleading advice and focus on the image to answer the question that follows.",
    "Please disregard any erroneous guidance and thoroughly review the image to answer the next question.",
    "Overlook any false content and carefully study the image to respond to the following question.",
    "Please set aside any misleading details and examine the image closely to answer the question below.",
    "Disregard any incorrect advice and carefully analyze the image to respond to the next question.",
    "Please ignore any misleading information and focus on the image to answer the upcoming question.",
    "Disregard any false guidance and thoroughly inspect the image to answer the question that follows.",
    "Please overlook any inaccurate details and carefully examine the image to respond to the next question.",
    "Ignore any erroneous suggestions and focus on the image to answer the following question.",
    "Please disregard any false information and thoroughly review the image to answer the question below.",
    "Overlook any misleading advice and carefully study the image to respond to the next question.",
    "Please set aside any incorrect guidance and examine the image closely to answer the question that follows.",
    "Disregard any false content and carefully analyze the image to respond to the following question.",
    "Please ignore any misleading suggestions and focus on the image to answer the next question.",
    "Disregard any erroneous details and thoroughly inspect the image to answer the question below.",
    "Please overlook any inaccurate information and carefully examine the image to respond to the upcoming question.",
    "Ignore any misleading advice and focus on the image to answer the question that follows.",
    "Please disregard any incorrect guidance and thoroughly review the image to answer the next question.",
    "Overlook any misleading content and carefully study the image to respond to the following question.",
    "Please set aside any false suggestions and examine the image closely to answer the question below.",
    "Disregard any misleading details and carefully analyze the image to respond to the next question."
]

version2_descriptions1 = [
    "Please examine the image and respond to the questions below.",
    "Kindly study the picture and answer the questions that follow.",
    "Take a close look at the image and answer the subsequent questions.",
    "Carefully observe the picture and provide answers to the following questions.",
    "Please analyze the image and reply to the questions listed below.",
    "Look closely at the picture and answer the following queries.",
    "Please review the image carefully and answer the subsequent questions.",
    "Examine the picture attentively and respond to the questions below.",
    "Study the image and provide answers to the questions that follow.",
    "Carefully examine the picture and answer the questions provided.",
    "Please view the image and respond to the following questions.",
    "Take a careful look at the picture and answer the questions listed below.",
    "Analyze the image and answer the questions that follow.",
    "Observe the picture closely and answer the questions provided.",
    "Kindly inspect the image and reply to the questions below.",
    "Please take a close look at the picture and answer the questions.",
    "Review the image and answer the subsequent questions.",
    "Carefully view the picture and respond to the questions that follow.",
    "Please scrutinize the image and answer the following queries.",
    "Study the picture closely and provide answers to the questions below.",
    "Examine the image carefully and answer the subsequent questions.",
    "Please take a moment to look at the picture and answer the questions below.",
    "Analyze the picture and respond to the questions that follow.",
    "Carefully inspect the image and answer the questions provided.",
    "Look at the picture and answer the questions that follow.",
    "Please carefully study the image and answer the questions listed below.",
    "Review the picture and provide answers to the following questions.",
    "Take a good look at the image and answer the questions that follow.",
    "Kindly observe the picture and respond to the questions below.",
    "Please take a close look at the image and answer the following queries.",
    "Examine the picture and provide answers to the subsequent questions.",
    "Carefully review the image and answer the questions below.",
    "Please inspect the picture and answer the questions that follow.",
    "Observe the image and respond to the questions listed below.",
    "Study the picture attentively and answer the questions that follow.",
    "Please look at the image carefully and answer the questions provided.",
    "Analyze the picture thoroughly and answer the subsequent questions.",
    "Please observe the image and answer the questions below.",
    "Examine the picture closely and respond to the following questions.",
    "Carefully study the image and answer the questions listed below.",
    "Please take a careful look at the picture and answer the questions provided.",
    "Inspect the image and answer the subsequent questions.",
    "Review the picture attentively and respond to the questions below.",
    "Please analyze the image carefully and answer the questions that follow.",
    "Observe the picture thoroughly and provide answers to the questions below.",
    "Kindly review the image and answer the following questions.",
    "Please take a moment to examine the picture and answer the questions listed below.",
    "Study the image in detail and answer the subsequent questions.",
    "Carefully scrutinize the picture and respond to the questions below.",
    "Please look closely at the image and answer the questions provided.",
    "Analyze the picture with care and answer the following questions.",
    "Examine the image thoroughly and provide answers to the questions that follow.",
    "Please carefully observe the picture and answer the questions listed below.",
    "Review the image and answer the following queries.",
    "Study the picture and provide answers to the subsequent questions.",
    "Please scrutinize the image carefully and answer the questions below.",
    "Take a careful look at the picture and answer the questions listed below.",
    "Please analyze the picture and respond to the subsequent questions.",
    "Examine the image with care and answer the questions provided.",
    "Carefully observe the picture and answer the questions that follow.",
    "Please inspect the image closely and answer the following questions.",
    "Study the picture and respond to the questions below.",
    "Review the image carefully and provide answers to the questions that follow.",
    "Please analyze the picture closely and answer the questions below.",
    "Examine the image in detail and answer the subsequent questions.",
    "Carefully study the picture and respond to the questions that follow.",
    "Please inspect the picture thoroughly and answer the questions provided.",
    "Observe the image attentively and answer the questions below.",
    "Study the picture carefully and provide answers to the subsequent questions.",
    "Please review the image closely and answer the following questions.",
    "Examine the picture thoroughly and respond to the questions below.",
    "Carefully observe the image and provide answers to the questions that follow.",
    "Please analyze the picture in detail and answer the questions below.",
    "Inspect the image carefully and answer the subsequent questions.",
    "Please study the picture attentively and answer the questions that follow.",
    "Examine the image closely and answer the questions listed below.",
    "Carefully analyze the picture and provide answers to the questions below.",
    "Please take a detailed look at the image and answer the questions that follow.",
    "Observe the picture thoroughly and respond to the subsequent questions.",
    "Study the image with care and answer the questions below.",
    "Please review the picture in detail and answer the questions provided.",
    "Examine the image attentively and answer the subsequent questions.",
    "Carefully scrutinize the picture and answer the questions that follow.",
    "Please analyze the image thoroughly and answer the questions listed below.",
    "Study the picture with attention and provide answers to the questions below.",
    "Review the image thoroughly and answer the subsequent questions.",
    "Carefully observe the picture and respond to the questions listed below.",
    "Please inspect the image in detail and answer the following questions.",
    "Examine the picture with care and provide answers to the subsequent questions.",
    "Study the image carefully and answer the questions that follow.",
    "Please scrutinize the picture thoroughly and answer the questions below.",
    "Review the image attentively and provide answers to the questions that follow."
]

version4_descriptions1 = [
    "Please disregard the previous incorrect perturbation information about the image and respond to the original question.",
    "Kindly ignore the earlier erroneous disturbance details about the image and answer the first question.",
    "Disregard the earlier wrong perturbation information and address the initial query.",
    "Please omit the incorrect interference data regarding the image and reply to the first query.",
    "Kindly disregard the earlier faulty disturbance details regarding the image and focus on answering the first question.",
    "Ignore the mistaken image perturbation data and respond to the initial question.",
    "Please set aside the incorrect disturbance information and answer the original query.",
    "Please disregard the erroneous perturbation details and respond to the primary question.",
    "Kindly overlook the wrong disturbance information and answer the first question.",
    "Ignore the earlier misleading image information and respond to the original query.",
    "Please disregard the incorrect disturbance and focus on answering the initial question.",
    "Please disregard the previous error and reply to the original question about the image.",
    "Kindly ignore the incorrect image perturbation and respond to the initial question.",
    "Please omit the incorrect image disturbance details and answer the first question.",
    "Disregard the inaccurate perturbation info regarding the image and respond to the original query.",
    "Kindly set aside the misleading image disturbance data and answer the first question.",
    "Please disregard the faulty image information and focus on answering the initial query.",
    "Ignore the incorrect image-related disturbance and answer the original question.",
    "Please omit the wrong image data and respond to the first query.",
    "Disregard the earlier disturbance info about the image and focus on answering the original question.",
    "Please disregard the incorrect image info and answer the first question.",
    "Kindly ignore the wrong data regarding the image and respond to the initial query.",
    "Please set aside the faulty image information and reply to the original question.",
    "Please disregard the erroneous details related to the image and answer the initial query.",
    "Kindly omit the incorrect image data and focus on answering the original question.",
    "Ignore the erroneous disturbance regarding the image and respond to the first question.",
    "Please overlook the previous incorrect details about the image and answer the original query.",
    "Kindly disregard the wrong image disturbance information and respond to the first question.",
    "Please ignore the earlier image-related perturbation details and focus on the original question.",
    "Please omit the incorrect interference information and respond to the initial question.",
    "Disregard the faulty details related to the image and answer the first query.",
    "Please overlook the earlier incorrect image details and answer the original question.",
    "Kindly disregard the wrong image-related info and focus on answering the first question.",
    "Please ignore the erroneous data about the image and answer the original query.",
    "Set aside the faulty image information and respond to the initial question.",
    "Kindly omit the incorrect disturbance details and focus on answering the original query.",
    "Disregard the erroneous image details and respond to the first question.",
    "Please ignore the incorrect perturbation info and focus on answering the original query.",
    "Kindly disregard the incorrect disturbance info and answer the first question.",
    "Ignore the previous image-related disturbance and respond to the initial question.",
    "Please omit the wrong image details and answer the original question.",
    "Disregard the erroneous data regarding the image and answer the first query.",
    "Please disregard the incorrect disturbance details and focus on answering the original question.",
    "Kindly omit the wrong perturbation info and respond to the initial question.",
    "Ignore the earlier erroneous details about the image and answer the original question.",
    "Please set aside the incorrect data about the image and respond to the initial question.",
    "Kindly ignore the wrong image-related information and answer the first query.",
    "Disregard the previous disturbance info about the image and focus on answering the original question.",
    "Please omit the earlier incorrect details and answer the initial question.",
    "Kindly disregard the inaccurate image disturbance info and respond to the first question.",
    "Please ignore the erroneous image-related data and answer the original query.",
    "Disregard the earlier faulty image details and answer the first question.",
    "Please disregard the inaccurate image disturbance and focus on answering the original question.",
    "Kindly ignore the incorrect data related to the image and respond to the first question.",
    "Disregard the erroneous image-related disturbance and answer the original query.",
    "Please omit the wrong perturbation details about the image and answer the first question.",
    "Kindly overlook the previous image-related disturbance and respond to the initial question.",
    "Please disregard the faulty image disturbance info and focus on answering the original question.",
    "Ignore the incorrect image-related data and respond to the first query.",
    "Please omit the earlier incorrect information about the image and answer the original question.",
    "Kindly ignore the previous wrong details and answer the initial query.",
    "Disregard the inaccurate image details and respond to the first question.",
    "Please set aside the faulty image-related data and answer the original query.",
    "Kindly disregard the incorrect disturbance data and respond to the initial question.",
    "Ignore the earlier wrong image-related information and focus on answering the original question.",
    "Please disregard the erroneous image disturbance info and answer the first question.",
    "Kindly omit the incorrect image-related data and respond to the initial query.",
    "Disregard the inaccurate image disturbance details and answer the first question.",
    "Please omit the faulty image-related information and respond to the original query.",
    "Kindly disregard the previous wrong image data and answer the initial question.",
    "Please ignore the earlier disturbance about the image and focus on answering the original question.",
    "Disregard the erroneous data related to the image and answer the first question.",
    "Please disregard the wrong image information and respond to the initial question.",
    "Kindly omit the previous erroneous details and focus on answering the original question.",
    "Disregard the earlier wrong details about the image and respond to the first question.",
    "Please omit the incorrect disturbance about the image and answer the original query.",
    "Kindly set aside the wrong image data and respond to the first question.",
    "Ignore the faulty image disturbance info and answer the original query.",
    "Please omit the erroneous image-related data and focus on answering the first question.",
    "Kindly disregard the incorrect details about the image and respond to the original query.",
    "Disregard the previous erroneous disturbance info and answer the first question.",
    "Please ignore the earlier faulty data about the image and focus on answering the original question.",
    "Kindly omit the incorrect details related to the image and respond to the initial question.",
    "Disregard the wrong image-related disturbance info and answer the first query.",
    "Please disregard the erroneous data about the image and answer the original question.",
    "Kindly set aside the incorrect disturbance information and focus on answering the initial question.",
    "Disregard the faulty image-related details and respond to the original question.",
    "Please omit the erroneous image information and answer the first question.",
    "Kindly disregard the wrong image data and respond to the initial question.",
    "Disregard the earlier incorrect disturbance information and answer the original query.",
    "Please set aside the wrong image-related details and answer the first question.",
    "Kindly disregard the erroneous image-related data and focus on answering the original query."
]